function ThermalPhysics_GUI()

clc;
clear;

%% Physical Constants

kB = 1.380649e-23;          % Boltzmann Constant (J/K)
NA = 6.022e23;              % Avogadro Number

%% GUI Window

fig = figure( ...
    'Name', 'Maxwell-Boltzmann Speed Distribution Simulator', ...
    'NumberTitle', 'off', ...
    'Position', [100 100 750 550], ...
    'Resize', 'off', ...
    'Color', 'w');

%% Gas Data

gases = { ...
    'Carbon Dioxide (CO2)', ...
    'Helium (He)', ...
    'Hydrogen (H2)', ...
    'Ammonia (NH3)', ...
    'Neon (Ne)', ...
    'Sulfur Hexafluoride (SF6)', ...
    'Krypton (Kr)', ...
    'Radon (Rn)', ...
    'Water Vapor (H2O)', ...
    'Xenon (Xe)'};

molarMasses = [ ...
    44.01, ...
    4.00, ...
    2.02, ...
    17.03, ...
    20.18, ...
    146.06, ...
    83.80, ...
    222.00, ...
    18.02, ...
    131.29];               % g/mol

%% Limits

maxMolecules = 1e8;

%% GUI Components

uicontrol( ...
    'Style', 'text', ...
    'Position', [30 490 150 25], ...
    'String', 'Select Gas:', ...
    'FontSize', 11, ...
    'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'left');

gasPopup = uicontrol( ...
    'Style', 'popupmenu', ...
    'Position', [180 490 200 25], ...
    'String', gases, ...
    'Value', 10, ...
    'FontSize', 11);

%% Temperature

uicontrol( ...
    'Style', 'text', ...
    'Position', [30 450 150 25], ...
    'String', 'Temperature (K):', ...
    'FontSize', 11, ...
    'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'left');

tempEdit = uicontrol( ...
    'Style', 'edit', ...
    'Position', [180 450 200 25], ...
    'String', '300', ...
    'FontSize', 11);

%% Number of Molecules

uicontrol( ...
    'Style', 'text', ...
    'Position', [30 410 150 25], ...
    'String', 'Number of Molecules:', ...
    'FontSize', 11, ...
    'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'left');

moleculesEdit = uicontrol( ...
    'Style', 'edit', ...
    'Position', [180 410 200 25], ...
    'String', '1000000', ...
    'FontSize', 11);

%% Speed Range

uicontrol( ...
    'Style', 'text', ...
    'Position', [30 370 150 25], ...
    'String', 'Speed Range (m/s):', ...
    'FontSize', 11, ...
    'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'left');

speedRangeMinEdit = uicontrol( ...
    'Style', 'edit', ...
    'Position', [180 370 90 25], ...
    'String', '200', ...
    'FontSize', 11);

speedRangeMaxEdit = uicontrol( ...
    'Style', 'edit', ...
    'Position', [290 370 90 25], ...
    'String', '900', ...
    'FontSize', 11);

%% Run Button

uicontrol( ...
    'Style', 'pushbutton', ...
    'Position', [120 310 160 40], ...
    'String', 'Run Simulation', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'Callback', @runSimulation);

%% Axes

ax = axes( ...
    'Units', 'pixels', ...
    'Position', [420 90 300 420]);

xlabel(ax, 'Speed (m/s)');
ylabel(ax, 'Probability Density');
title(ax, 'Maxwell-Boltzmann Distribution');

grid(ax, 'on');

%% Output Text Area

outputText = uicontrol( ...
    'Style', 'edit', ...
    'Position', [30 40 360 240], ...
    'Max', 20, ...
    'Min', 1, ...
    'Enable', 'inactive', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Simulation Function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function runSimulation(~,~)

    cla(ax);

    set(outputText, 'String', '');

    %% Read Inputs

    gasIdx = get(gasPopup, 'Value');

    T = str2double(get(tempEdit, 'String'));

    N_molecules = str2double(get(moleculesEdit, 'String'));

    v_min = str2double(get(speedRangeMinEdit, 'String'));

    v_max = str2double(get(speedRangeMaxEdit, 'String'));

    %% Input Validation

    if isnan(T) || T <= 0

        errordlg('Please enter a valid positive temperature.', ...
            'Input Error');

        return;

    end

    if isnan(N_molecules) || N_molecules <= 0 ...
            || N_molecules > maxMolecules

        errordlg( ...
            ['Number of molecules must be between 1 and ', ...
            num2str(maxMolecules)], ...
            'Input Error');

        return;

    end

    if isnan(v_min) || isnan(v_max) ...
            || v_min < 0 || v_max <= v_min

        errordlg( ...
            'Please enter a valid speed range.', ...
            'Input Error');

        return;

    end

    %% Molecular Mass

    M = molarMasses(gasIdx);

    m = (M / 1000) / NA;

    %% Maxwell-Boltzmann PDF

    MB_pdf = @(v) ...
        4*pi * (m/(2*pi*kB*T))^(3/2) ...
        .* v.^2 ...
        .* exp(-m*v.^2/(2*kB*T));

    %% Theoretical Distribution

    v_plot = linspace(0, max(2000, v_max*1.3), 1000);

    P = MB_pdf(v_plot);

    %% Plot Theoretical Curve

    plot(ax, v_plot, P, ...
        'b-', ...
        'LineWidth', 2);

    hold(ax, 'on');

    %% Random Simulation

    % Limit simulation size for memory safety
    N_sim = min(N_molecules, 1e6);

    vx = randn(N_sim,1);
    vy = randn(N_sim,1);
    vz = randn(N_sim,1);

    v_sim = sqrt(vx.^2 + vy.^2 + vz.^2);

    v_sim = v_sim * sqrt(kB*T/m);

    %% Histogram of Simulated Data

    histogram(ax, v_sim, 60, ...
        'Normalization', 'pdf', ...
        'FaceAlpha', 0.4);

    %% Probability in Selected Range

    v_fine = linspace(v_min, v_max, 1000);

    prob_theoretical = trapz(v_fine, MB_pdf(v_fine));

    simulated_count = sum(v_sim >= v_min & v_sim <= v_max);

    prob_simulated = simulated_count / N_sim;

    estimated_molecules = prob_theoretical * N_molecules;

    %% Theoretical Speeds

    v_mp = sqrt(2*kB*T/m);

    v_mean = sqrt(8*kB*T/(pi*m));

    v_rms = sqrt(3*kB*T/m);

    %% Simulated Speeds

    v_mean_sim = mean(v_sim);

    v_rms_sim = sqrt(mean(v_sim.^2));

    v_mp_sim = mode(round(v_sim));

    %% Percentage Errors

    err_mean = abs(v_mean_sim - v_mean)/v_mean * 100;

    err_rms = abs(v_rms_sim - v_rms)/v_rms * 100;

    err_mp = abs(v_mp_sim - v_mp)/v_mp * 100;

    %% Output Text

    outStr = sprintf( ...
        'Gas: %s\n\n', gases{gasIdx});

    outStr = [outStr, ...
        sprintf('Temperature = %.2f K\n', T)];

    outStr = [outStr, ...
        sprintf('Number of Molecules = %.0f\n', N_molecules)];

    outStr = [outStr, ...
        sprintf('Simulation Samples = %.0f\n\n', N_sim)];

    outStr = [outStr, ...
        sprintf('Speed Range = %.1f to %.1f m/s\n\n', ...
        v_min, v_max)];

    %% Probabilities

    outStr = [outStr, ...
        sprintf('Theoretical Probability = %.5f\n', ...
        prob_theoretical)];

    outStr = [outStr, ...
        sprintf('Simulated Probability = %.5f\n', ...
        prob_simulated)];

    outStr = [outStr, ...
        sprintf('Estimated Molecules in Range = %.0f\n\n', ...
        estimated_molecules)];

    %% Most Probable Speed

    outStr = [outStr, ...
        sprintf('Most Probable Speed (Theory) = %.2f m/s\n', ...
        v_mp)];

    outStr = [outStr, ...
        sprintf('Most Probable Speed (Simulation) = %.2f m/s\n', ...
        v_mp_sim)];

    outStr = [outStr, ...
        sprintf('Percentage Error = %.3f %%\n\n', ...
        err_mp)];

    %% Mean Speed

    outStr = [outStr, ...
        sprintf('Mean Speed (Theory) = %.2f m/s\n', ...
        v_mean)];

    outStr = [outStr, ...
        sprintf('Mean Speed (Simulation) = %.2f m/s\n', ...
        v_mean_sim)];

    outStr = [outStr, ...
        sprintf('Percentage Error = %.3f %%\n\n', ...
        err_mean)];

    %% RMS Speed

    outStr = [outStr, ...
        sprintf('RMS Speed (Theory) = %.2f m/s\n', ...
        v_rms)];

    outStr = [outStr, ...
        sprintf('RMS Speed (Simulation) = %.2f m/s\n', ...
        v_rms_sim)];

    outStr = [outStr, ...
        sprintf('Percentage Error = %.3f %%\n', ...
        err_rms)];

    set(outputText, 'String', outStr);

    %% Highlight Speed Range

    yLimits = ylim(ax);

    fill(ax, ...
        [v_min v_max v_max v_min], ...
        [0 0 yLimits(2) yLimits(2)], ...
        'r', ...
        'FaceAlpha', 0.1, ...
        'EdgeColor', 'none');

    %% Legend

    legend(ax, ...
        'Theoretical Distribution', ...
        'Simulated Data', ...
        'Selected Speed Range');

    hold(ax, 'off');

end

end